import type { NextPage } from "next";
import Head from "next/head";

import { useRouter } from "next/router";

const Resolver: NextPage = () => {
  const router = useRouter();
  const did = router.query.did as string;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <code>{did}</code>
      </main>
    </div>
  );
};

export default Resolver;
