import type { NextPage } from "next";
import Head from "next/head";

import { useRouter } from "next/router";

const Resolver: NextPage = () => {
  const router = useRouter();
  const did = router.query.did as string;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:img"
          content="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Portale_Leonardo_da_Vinci.png/100px-Portale_Leonardo_da_Vinci.png"
        />
      </Head>

      <main>
        <code>{did}</code>
      </main>
    </div>
  );
};

export default Resolver;
