name: DID Web

on:
  push:
    branches:
      - main
  # schedule:
  #   # Every day at midnight
  #   - cron: "0 0 * * *"
  # workflow_dispatch:

jobs:
  did_web:
    name: Publish DID Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Registry
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
          publish_dir: "./docs"
          exclude_assets: ".github"
