name: Documentation

on:
  push:
    branches:
      - main
  # schedule:
  #   # Every day at midnight
  #   - cron: "0 0 * * *"
  # workflow_dispatch:

jobs:
  publish_documentation:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a Verifiable Credential
        id: create_credential
        uses: transmute-industries/verifiable-actions@v0.0.15
        with:
          resource: "credential"
          action: "create"
          username: "OR13"
          repository: "didme.me"
          mnemonic: "${{ secrets.MNEMONIC }}"
          hd-path: "m/44'/0'/0'/0/0"
          key-type: "ed25519"
          vc-format: "vc"
          file-input: "./docs/sbom.template.json"
          file-output: "./docs/sbom.json"

      - name: View Example
        run: |-
          cat ./docs/sbom.json

      - name: Publish Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
          publish_dir: "./docs"
          exclude_assets: ".github"
